### ISSUE TITLE
deploy versjoner som håndterer informasjonsmodeller

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/rdf-diff-store#30]
Idag kjøres kun `fdk-dataset-rdf-diff-writer` og `fdk-dataset-rdf-query-cache` den må også konfigureres til å kunne kjøres opp for informasjonsmodeller, feks som `fdk-information-model-rdf-diff-writer` og `fdk-information-model-rdf-query-cache`

Trengs for at reports-bff skal klare å hente historiske data ang. informasjonsmodeller

**Comment by valosnah** [comment]
Arkiveres, lukkes
